---
title: Recipes
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  recipes:
    title: recipes
    output: true

    #basic layout template
    - scope:
        path: ''
        type: posts
      values:
        layout: basic
        image: ''
        tags: []

    #recipe layout template
    - scope:
        path: ''
        type: posts
      values:
        layout: recipe
        image: ''
        tags: []
        source: "[site name or book name]"
        sourceURL: ''
        sourceAuthor: by [Author], p[n]
        yield: Makes []
        authorNote: ''
        personalNote: ''
        totalTime: ''
        prepTime: ''
        handsoffTime: ''
        cookTime: ''
        chillTime: ''
        assemblyTime: ''
        reheatTime: ''
        ingredients: "⅛ ¼ ⅓ ½ ⅔ ¾ fractions"
