---
title: Recipes
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

  # custom collections for recipes and tags
  recipes:
    title: Recipes
    output: true
    permalink: /recipes/:path
    slug: recipes
  my_tags:
    output: true
    permalink: /tag/:name


defaults:

  # default post type
- scope:
    path: ''
    type: posts
  values:
    layout: default
    image: ''
    tags: []

  # default page type
- scope:
    path: ''
    type: pages
  values:
    layout: default
    image: ''
    tags: []

  # recipe template
- scope:
    path: ''
    type: recipes
  values:
    layout: recipe
    image: ''
    tags: []
    source: "[site name or book name]"
    sourceURL: ''
    sourceAuthor: by [Author], p[n]
    yield: Makes []
    authorNote: ''
    personalNote: ''
    totalTime: ''
    prepTime: ''
    handsoffTime: ''
    cookTime: ''
    chillTime: ''
    assemblyTime: ''
    reheatTime: ''
    ingredients: "⅛ ¼ ⅓ ½ ⅔ ¾ fractions"
- scope:
    path: ''
    type: posts
  values:
    layout: weekly-list
    image: ''
    tags: []
