---
title: Recipes
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  recipes:
    title: Recipes
    output: true
  defaults:

    -
      scope:
        path: ""
        type: posts
      values:
        layout: default
        image: ""
        tags: []

    -
      scope:
        path: ""
        type: posts
      values:
        layout: recipe
        image: ""
        tags: []
        source: "[site name or book name]"
        sourceURL: ""
        sourceAuthor: by [Author], p[n]
        yield: Makes []
        authorNote: ""
        personalNote: ""
        totalTime: ""
        prepTime: ""
        handsoffTime: ""
        cookTime: ""
        chillTime: ""
        assemblyTime: ""
        reheatTime: ""
        ingredients: "⅛ ¼ ⅓ ½ ⅔ ¾ fractions"
