---
title: Recipes
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
    title: Recipes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
    image: ''
    tags: []
- scope:
    path: ''
    type: pages
  values:
    layout: default
    image: ''
    tags: []
- scope:
    path: recipes
    type: posts
  values:
    layout: recipe
    image: ''
    tags: []
    source: "[site name or book name]"
    sourceURL: ''
    sourceAuthor: by [Author], p[n]
    yield: Makes []
    authorNote: ''
    personalNote: ''
    totalTime: ''
    prepTime: ''
    handsoffTime: ''
    cookTime: ''
    chillTime: ''
    assemblyTime: ''
    reheatTime: ''
    ingredients: "⅛ ¼ ⅓ ½ ⅔ ¾ fractions"
- scope:
    path: week-of
    type: posts
  values:
    layout: weekly-list
    image: ''
    tags: []
